image: maven:latest

#cache:
#  paths:
#    - .m2/repository/
#    - target/

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

maven_job:
  script:
    - mvn $MAVEN_CLI_OPTS test
