image: java:8

stages:
  - build
  - integrationtest

before_script:
  - chmod +x mvnw

build:
  stage: build
  script:
    - "./mvnw package"
  artifacts:
    paths:
      - target/spring-cloud-streams-playground-0.0.1-SNAPSHOT.jar

integrationtest:
  stage: integrationtest
  script:
    - "./mvnw verify"
